name: first_pipeline

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  authentification_and_push:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-22.04

    steps:
      - name: Recuperation du code
        uses: actions/checkout@v4

      - name: Authentification de Github Actions A GCP
        uses: google-github-actions/auth@v3
        with:
          project_id: 'agentic-ai-learning-486e'
          workload_identity_provider: 'projects/80844171008/locations/global/workloadIdentityPools/github-actions-hmj01-pool/providers/github-provider'
          service_account: github-actions-sa@agentic-ai-learning-486e.iam.gserviceaccount.com

      - name: Authentifie Docker Aupres de Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Taguer l'image selon la norme
        run: docker image build . -t europe-west1-docker.pkg.dev/agentic-ai-learning-486e/hmj01-repo/nginx-demo:v1
      
      - name: Patarge L'Image Dans La Registry GCP
        run: docker  push  europe-west1-docker.pkg.dev/agentic-ai-learning-486e/hmj01-repo/nginx-demo:v1
      
      - name: Check si l'image A Ete Cree
        run: docker image ls | grep europe-west1-docker.pkg.dev/agentic-ai-learning-486e/hmj01-repo/nginx-demo:v1

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Check si l'image est dans la registy GCP
        run: gcloud artifacts docker images list europe-west1-docker.pkg.dev/agentic-ai-learning-486e/hmj01-repo | grep nginx-demo:v1
        