name: first_pipeline


env:
  IMAGE_NAME: europe-west1-docker.pkg.dev/agentic-ai-learning-486e/hmj01-repo/my-nginx
      
  IMAGE_TAG: ${{github.sha}}

  CONTAINER_NAME: nginx-test


on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du code source
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09  # v5

      - name: Build du Dockerfile
        run: docker image build . -t mon-image
      
      - name: Lancement du container
        run: docker container run -d -p 8080:80 --name $CONTAINER_NAME  mon-image
      
      - name: Attendre le demarrage
        run: |

            for i in {1..5}; do

              if curl -f http://127.0.0.1:8080; then
                echo "Service disponible !"
                exit 0
              fi
  
              echo "Service pas encore disponible, nouvelle tentative..."
              sleep 5
            done
            echo "Le service n'est pas disponible après 20 secondes"
            exit 1

      - name: Arrêter et supprimer le container
        if: always()
        run: |
           docker container stop $CONTAINER_NAME || true
           docker container rm $CONTAINER_NAME || true


  authentification_and_push:
    needs: [test]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Recuperation du code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Authentification de Github Actions A GCP
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          project_id: 'agentic-ai-learning-486e'
          workload_identity_provider: 'projects/80844171008/locations/global/workloadIdentityPools/github-actions-hmj01-pool/providers/github-provider'
          service_account: github-actions-sa@agentic-ai-learning-486e.iam.gserviceaccount.com
     
      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Authentifie Docker Aupres de Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Taguer l'image selon la norme
        run: docker image build . -t $IMAGE_NAME:$IMAGE_TAG

      - name: Identifier les vulnerabilites
        uses: aquasecurity/trivy-action@a9c7b0f06e461e9d4b4d1711f154ee024b8d7ab8 #v0.36.0
        with:
          image-ref: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} #europe-west1-docker.pkg.dev/agentic-ai-learning-486e/hmj01-repo/my-nginx
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Patarge L'Image Dans La Registry GCP
        run: docker  push  $IMAGE_NAME:$IMAGE_TAG
      
      - name: Check si l'image A Ete Cree
        run: docker image ls | grep $IMAGE_NAME

      - name: Check si l'image est dans la registy GCP
        run: gcloud artifacts docker images list europe-west1-docker.pkg.dev/agentic-ai-learning-486e/hmj01-repo --include-tags | grep $IMAGE_TAG
      
      - name: Deploiement Du Container Dans GCP 
        run: gcloud run deploy $CONTAINER_NAME --no-allow-unauthenticated --image=$IMAGE_NAME:$IMAGE_TAG  --region=europe-west1  --port=80